### PR TITLE
Code review benefits

### PR DESCRIPTION
**Pull request by rmacken98**
Added benefits for code reviews

### CODE REVIEW

**Comment by seanymcelroy** [comment]
Those code review benefits look good!
In terms of formatting I believe each benefit **heading** should be distinguished from the explanation.

**Comment by Lordjiggyx** [comment]
I agree with Sean please use headings to distinguish the points but otherwise content looks good

**Comment by NicBoi** [comment]
Looks good. Agree with Sean, having some titles for each benefit would make it more readable

**Comment by rmacken98** [comment]
> Those code review benefits look good!
> In terms of formatting I believe each benefit **heading** should be distinguished from the explanation.

Good suggestion will make changes before merge.

**Comment by Lordjiggyx** [comment]
Looks good to merge

**Pull request merged**
