### PR TITLE
Coding standards refactor categories

### PR DESCRIPTION
**Pull request by seanymcelroy**
1. Sepearted  coding standard Categories to new file.
2. Updated quick links.
3. Updated images.

### CODE REVIEW

**Comment by Lordjiggyx** [comment]
Real good work happy for the merge

**Comment by NicBoi** [comment]
Minor spelling mistakes could be fixed in "BadPracticesCodingStandards.md", other than that, looks very good

**Comment by seanymcelroy** [comment]
> Minor spelling mistakes could be fixed in "BadPracticesCodingStandards.md", other than that, looks very good

Thanks for notifying me!
Fixed some of the grammatical errors.

**Review by rmacken98 — APPROVED** [review]
Looks good Sean.

**Review by NicBoi — APPROVED** [review]

**Pull request merged**
